#! /bin/sh
#
# Run the test suite to generate some sample inputs
#
set -e
[ -x configure ] || ./autogen.sh
./configure CPPFLAGS=-DLOG_INPUT
make clean
make
mkdir -p fuzzing/gesftpserver/testcase_dir
SFTPSERVER_INPUT_LOG_DIR=$(pwd)/fuzzing/gesftpserver/testcase_dir
make check
