#! /usr/bin/env python2.4
import os,sys,re,string
from subprocess import Popen,PIPE,STDOUT

srcdir = os.path.abspath(os.getenv('srcdir'))
builddir = os.path.abspath('.')
client = os.path.abspath("sftpclient")
server = os.path.abspath("gesftpserver")

def rmrf(path):
    if os.path.lexists(path):
        if os.path.isdir(path):
            for name in os.listdir(path):
                rmrf(os.path.join(path,name))
            os.rmdir(path)
        else:
            os.remove(path)

os.umask(022)                           # for consistent permissions
failed = 0

for test in os.listdir(os.path.join(srcdir, 'tests')):
    for proto in ['3', '4', '5', '6']:
        if ('.' in test
            or not proto in test
            or '~' in test):
            continue
        sys.stderr.write("Testing %s protocol %s ... " % (test, proto))
        root = os.path.join(builddir, ',testroot','%s.%s' % (test, proto))
        rmrf(root)
        os.makedirs(root)
        os.chdir(root)
        output = Popen([client, "-S", proto, "-P", server,
                        "-b", os.path.join(srcdir, 'tests', test),
                        '--no-stop-on-error'],
                       stdout=PIPE,
                       stderr=STDOUT).communicate()[0].split('\n')
        if output[len(output)-1] == "":
            output = output[:-1]
        n = 0
        errors = []
        for expected in file(os.path.join(srcdir, 'tests',
                                          '%s.expect' % test)):
            expected = expected[:-1]    # strip newline
	    if n >= len(output):
                errors.append("EXPECTED: %s" % expected)
                errors.append("     GOT: EOF")
                break
            got = output[n]
            n += 1
            try:
                if not re.match(expected, got):
                    errors.append("EXPECTED: %s" % expected)
                    errors.append("     GOT: %s" % got)
            except:
                print "\n\nPossible invalid regexp:\n%s\n" % expected
                raise
        if n < len(output):
            errors.append("   EXTRA: %s" % output[n])
        if len(errors) > 0:
            sys.stderr.write("FAILED\n")
            sys.stderr.write(string.join(errors, '\n'))
            sys.stderr.write("\n")
            failed += 1
        else:
            sys.stderr.write("passed\n")

if errors:
    print "%d test failed" % failed
    sys.exit(1)
else:
    print "OK"

